name: Run tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1208
      - name: Run tests
        run: clj -Atest

